import AppKit
import PDFKit

@MainActor enum ExportService {
 static func render(_ board:Board,size:CGSize=CGSize(width:1600,height:1000),transparent:Bool=false)->NSImage{let image=NSImage(size:size);image.lockFocus();if !transparent{NSColor.white.setFill();NSBezierPath(rect:CGRect(origin:.zero,size:size)).fill()};for e in board.elements{let color=NSColor(red:e.stroke.red,green:e.stroke.green,blue:e.stroke.blue,alpha:e.stroke.alpha*e.opacity);color.setStroke();if e.kind == .stroke || e.kind == .highlighter{let p=NSBezierPath();if let first=e.points.first{p.move(to:first.cgPoint);for q in e.points.dropFirst(){p.line(to:q.cgPoint)}};p.lineWidth=e.width;p.lineCapStyle = .round;p.stroke()}else if let text=e.text{(text as NSString).draw(in:e.bounds.cgRect,withAttributes:[.font:NSFont.systemFont(ofSize:e.fontSize),.foregroundColor:color])}else{let p=NSBezierPath(rect:e.bounds.cgRect);p.lineWidth=e.width;p.stroke()}};image.unlockFocus();return image}
 static func copyPNG(_ board:Board){let image=render(board);NSPasteboard.general.clearContents();NSPasteboard.general.writeObjects([image])}
 static func exportPDF(_ board:Board){let panel=NSSavePanel();panel.allowedContentTypes=[.pdf];panel.nameFieldStringValue="\(board.name).pdf";guard panel.runModal()= = .OK,let url=panel.url else{return};let image=render(board);guard let data=image.tiffRepresentation,let rep=NSBitmapImageRep(data:data)else{return};let pdf=rep.cgImage.flatMap{PDFPage(image:NSImage(cgImage:$0,size:image.size))}.flatMap{page->PDFDocument? in let d=PDFDocument();d.insert(page,at:0);return d};pdf?.write(to:url)}
 static func exportPNG(_ board:Board,transparent:Bool=false){let p=NSSavePanel();p.allowedContentTypes=[.png];p.nameFieldStringValue="\(board.name).png";guard p.runModal()= = .OK,let u=p.url,let t=render(board,transparent:transparent).tiffRepresentation,let b=NSBitmapImageRep(data:t),let d=b.representation(using:.png,properties:[:])else{return};try? d.write(to:u)}
}
