@preconcurrency import AVFoundation
import Accelerate
import CoreImage

final class CameraMarkerTracker:NSObject,MarkerTracking,@unchecked Sendable{
 var onFrame:(@Sendable (MarkerFrame)->Void)?;var profile=ColorProfile(name:"Red marker",hue:0,saturation:0.8,value:0.8);let session=AVCaptureSession();private let queue=DispatchQueue(label:"slate.camera",qos:.userInteractive);private var lastTime=0.0
 func start(){Task{@MainActor in switch AVCaptureDevice.authorizationStatus(for:.video){case .authorized:self.configure();case .notDetermined:if await AVCaptureDevice.requestAccess(for:.video){self.configure()};default:break}}}
 @MainActor private func configure(){guard session.inputs.isEmpty,let device=AVCaptureDevice.default(for:.video),let input=try? AVCaptureDeviceInput(device:device),session.canAddInput(input)else{return};session.beginConfiguration();session.sessionPreset = .low;session.addInput(input);let output=AVCaptureVideoDataOutput();output.alwaysDiscardsLateVideoFrames=true;output.videoSettings=[kCVPixelBufferPixelFormatTypeKey as String:kCVPixelFormatType_32BGRA];output.setSampleBufferDelegate(self,queue:queue);if session.canAddOutput(output){session.addOutput(output)};session.commitConfiguration();queue.async{self.session.startRunning()}}
 func stop(){queue.async{self.session.stopRunning()}}
 private func detect(_ pixelBuffer:CVPixelBuffer)->[MarkerBlob]{CVPixelBufferLockBaseAddress(pixelBuffer,.readOnly);defer{CVPixelBufferUnlockBaseAddress(pixelBuffer,.readOnly)};guard let base=CVPixelBufferGetBaseAddress(pixelBuffer)else{return[]};let w=CVPixelBufferGetWidth(pixelBuffer),h=CVPixelBufferGetHeight(pixelBuffer),rowBytes=CVPixelBufferGetBytesPerRow(pixelBuffer);let step=max(2,w/160);let bytes=base.assumingMemoryBound(to:UInt8.self);var points:[CGPoint]=[];for y in stride(from:0,to:h,by:step){for x in stride(from:0,to:w,by:step){let i=y*rowBytes+x*4;let hsv=HSVPixel.from(r:Double(bytes[i+2])/255,g:Double(bytes[i+1])/255,b:Double(bytes[i])/255);if hsv.matches(profile){points.append(CGPoint(x:Double(x)/Double(w),y:Double(y)/Double(h)))}}};guard !points.isEmpty else{return[]};let midpoint=0.5;let groups=Dictionary(grouping:points){$0.x<midpoint ? 0:1};return groups.values.compactMap{g in guard g.count>=profile.minimumBlobSize/step else{return nil};return MarkerBlob(centroid:CGPoint(x:g.map(\.x).reduce(0,+)/Double(g.count),y:g.map(\.y).reduce(0,+)/Double(g.count)),area:g.count*step*step)} }
}
extension CameraMarkerTracker:AVCaptureVideoDataOutputSampleBufferDelegate{func captureOutput(_ output:AVCaptureOutput,didOutput sampleBuffer:CMSampleBuffer,from connection:AVCaptureConnection){let now=CMSampleBufferGetPresentationTimeStamp(sampleBuffer).seconds;guard now-lastTime>1.0/30,let buffer=CMSampleBufferGetImageBuffer(sampleBuffer)else{return};lastTime=now;onFrame?(MarkerFrame(timestamp:now,blobs:detect(buffer)))}}
