import Foundation
import CoreGraphics

enum GuideLayout:String,CaseIterable{case flowchart,mindMap,stepCards,timeline,checklist,comparison}
struct GuideNode:Equatable{enum Kind:Equatable{case heading,bullet,step,arrow,comparison,date,text};var kind:Kind;var text:String;var level:Int}
struct VisualGuideParser{
 func parse(_ text:String)->[GuideNode]{text.split(separator:"\n",omittingEmptySubsequences:true).map{raw in let line=String(raw).trimmingCharacters(in:.whitespaces);let level=raw.prefix{ $0==" " }.count/2;if line.hasPrefix("#"){return GuideNode(kind:.heading,text:line.trimmingCharacters(in:CharacterSet(charactersIn:"# ")),level:level)};if line.range(of:"^\\d+[.)] ",options:.regularExpression) != nil{return GuideNode(kind:.step,text:line.replacingOccurrences(of:"^\\d+[.)] ",with:"",options:.regularExpression),level:level)};if line.hasPrefix("- ")||line.hasPrefix("* "){return GuideNode(kind:.bullet,text:String(line.dropFirst(2)),level:level)};if line.contains(" -> "){return GuideNode(kind:.arrow,text:line,level:level)};if line.range(of:"\\bvs\\.?\\b",options:[.regularExpression,.caseInsensitive]) != nil{return GuideNode(kind:.comparison,text:line,level:level)};if line.range(of:"\\b(19|20)\\d{2}\\b",options:.regularExpression) != nil{return GuideNode(kind:.date,text:line,level:level)};return GuideNode(kind:.text,text:line,level:level)}}
 func makeElements(from text:String,layout:GuideLayout,origin:CGPoint)->[BoardElement]{let nodes=parse(text);var out:[BoardElement]=[];let card=CGSize(width:220,height:96);for (i,n) in nodes.enumerated(){let position:CGPoint=switch layout{case .mindMap:CGPoint(x:origin.x+cos(Double(i)*1.1)*260,y:origin.y+sin(Double(i)*1.1)*190);case .timeline:CGPoint(x:origin.x+Double(i)*250,y:origin.y+(i%2==0 ? 0:130));case .comparison:CGPoint(x:origin.x+Double(i%2)*250,y:origin.y+Double(i/2)*120);default:CGPoint(x:origin.x,y:origin.y+Double(i)*120)};let fill=n.kind == .heading ? RGBAColor(red:0.83,green:0.29,blue:0.2,alpha:0.12):RGBAColor(red:0.5,green:0.5,blue:0.5,alpha:0.06);out.append(BoardElement(kind:.shape,bounds:RectValue(x:position.x,y:position.y,width:card.width,height:card.height),shape:.rectangle,fill:fill,width:1));out.append(BoardElement(kind:.text,bounds:RectValue(x:position.x+12,y:position.y+12,width:card.width-24,height:card.height-24),text:(layout == .checklist ? "☐ ":"")+n.text,fontSize:n.kind == .heading ? 20:16));if i>0{let previous=out[out.count-4].bounds;out.append(BoardElement(kind:.connector,bounds:RectValue(x:previous.x+card.width,y:previous.y+card.height/2,width:position.x-previous.x-card.width,height:position.y-previous.y),shape:.arrow,width:1.5))}};return out}
}
