import SwiftUI
import AppKit
import MetalKit

struct SlateCanvas:NSViewRepresentable{
 @EnvironmentObject var store:BoardStore
 func makeNSView(context:Context)->CanvasHostView{let v=CanvasHostView();v.store=store;return v}
 func updateNSView(_ v:CanvasHostView,context:Context){v.store=store;v.needsDisplay=true}
}

@MainActor final class CanvasHostView:NSView,MTKViewDelegate{
 weak var store:BoardStore?; private let metalView:MTKView; private var live:[CanvasPoint]=[]; private var dragStart:CGPoint?; private var laser:[(CGPoint,Date)]=[]
 override var isFlipped:Bool{true}; override var acceptsFirstResponder:Bool{true}
 override init(frame:NSRect){let device=MTLCreateSystemDefaultDevice();metalView=MTKView(frame:frame,device:device);super.init(frame:frame);wantsLayer=true;metalView.delegate=self;metalView.isPaused=false;metalView.enableSetNeedsDisplay=false;metalView.preferredFramesPerSecond=NSScreen.main?.maximumFramesPerSecond ?? 60;metalView.framebufferOnly=true;addSubview(metalView,position:.below,relativeTo:nil);registerForDraggedTypes([.fileURL,.string,.tiff,.png]);allowedTouchTypes=[.indirect]}
 required init?(coder:NSCoder){fatalError()}
 override func layout(){super.layout();metalView.frame=bounds}
 func mtkView(_ view:MTKView,drawableSizeWillChange size:CGSize){}
 func draw(in view:MTKView){guard let pass=view.currentRenderPassDescriptor,let drawable=view.currentDrawable,let queue=view.device?.makeCommandQueue(),let command=queue.makeCommandBuffer(),let encoder=command.makeRenderCommandEncoder(descriptor:pass)else{return};let dark=effectiveAppearance.bestMatch(from:[.darkAqua,.aqua]) == .darkAqua;pass.colorAttachments[0].clearColor=dark ? MTLClearColorMake(0.075,0.078,0.085,1):MTLClearColorMake(0.975,0.973,0.96,1);encoder.endEncoding();command.present(drawable);command.commit()}
 override func draw(_ dirtyRect:NSRect){super.draw(dirtyRect);guard let store,let context=NSGraphicsContext.current?.cgContext else{return};context.saveGState();context.translateBy(x:store.pan.width,y:store.pan.height);context.scaleBy(x:store.zoom,y:store.zoom);drawBackground(context,store.current.background);for e in store.current.elements.sorted(by:{$0.zIndex<$1.zIndex}){draw(e,context:context,selected:store.selection.contains(e.id))};if !live.isEmpty{drawPath(live,color:toolColor(store.tool),width:toolWidth(store.tool),opacity:store.tool == .highlighter ? 0.28:1,context:context)};context.restoreGState()}
 private func drawBackground(_ c:CGContext,_ background:CanvasBackground){guard background != .blank else{return};c.setStrokeColor(NSColor.separatorColor.withAlphaComponent(0.22).cgColor);c.setFillColor(NSColor.separatorColor.withAlphaComponent(0.32).cgColor);let area=CGRect(x:-5000,y:-5000,width:10000,height:10000);switch background{case .dots:for x in stride(from:-5000,through:5000,by:24){for y in stride(from:-5000,through:5000,by:24){c.fillEllipse(in:CGRect(x:x,y:y,width:1.5,height:1.5))}}case .grid:for x in stride(from:-5000,through:5000,by:24){c.move(to:CGPoint(x:x,y:-5000));c.addLine(to:CGPoint(x:x,y:5000))};for y in stride(from:-5000,through:5000,by:24){c.move(to:CGPoint(x:-5000,y:y));c.addLine(to:CGPoint(x:5000,y:y))};c.strokePath();case .lines:for y in stride(from:-5000,through:5000,by:24){c.move(to:CGPoint(x:-5000,y:y));c.addLine(to:CGPoint(x:5000,y:y))};c.strokePath();default:_=area}}
 private func draw(_ e:BoardElement,context c:CGContext,selected:Bool){c.saveGState();c.setAlpha(e.opacity);let stroke=NSColor(red:e.stroke.red,green:e.stroke.green,blue:e.stroke.blue,alpha:e.stroke.alpha).cgColor;c.setStrokeColor(stroke);c.setLineWidth(e.width);if e.pattern == .dashed{c.setLineDash(phase:0,lengths:[10,6])};if e.pattern == .dotted{c.setLineDash(phase:0,lengths:[2,6]);c.setLineCap(.round)}
  if e.kind == .stroke || e.kind == .highlighter{drawPath(e.points,color:e.stroke,width:e.width,opacity:e.kind == .highlighter ? 0.3:e.opacity,context:c)} else if e.kind == .text || e.kind == .sticky{if e.kind == .sticky{c.setFillColor((e.fill.map{NSColor(red:$0.red,green:$0.green,blue:$0.blue,alpha:$0.alpha)} ?? NSColor.systemYellow.withAlphaComponent(0.25)).cgColor);c.fill(e.bounds.cgRect)};let attr:[NSAttributedString.Key:Any]=[.font:NSFont(name:e.fontName,size:e.fontSize) ?? .systemFont(ofSize:e.fontSize),.foregroundColor:NSColor(cgColor:stroke) ?? .labelColor];(e.text ?? "Text").draw(in:e.bounds.cgRect.insetBy(dx:8,dy:8),withAttributes:attr)} else {let r=e.bounds.cgRect;if let f=e.fill{c.setFillColor(NSColor(red:f.red,green:f.green,blue:f.blue,alpha:f.alpha).cgColor);shapePath(e.shape,r,c);c.fillPath()};shapePath(e.shape,r,c);c.strokePath();if e.shape == .arrow{c.move(to:CGPoint(x:r.maxX-10,y:r.midY-7));c.addLine(to:CGPoint(x:r.maxX,y:r.midY));c.addLine(to:CGPoint(x:r.maxX-10,y:r.midY+7));c.strokePath()}}
  if selected{c.setStrokeColor(NSColor.controlAccentColor.cgColor);c.setLineWidth(1);c.setLineDash(phase:0,lengths:[4,3]);c.stroke(e.bounds.cgRect.insetBy(dx:-5,dy:-5));for p in [CGPoint(x:e.bounds.x-7,y:e.bounds.y-7),CGPoint(x:e.bounds.x+e.bounds.width+3,y:e.bounds.y+e.bounds.height+3)]{c.fill(CGRect(origin:p,size:CGSize(width:8,height:8)))}};c.restoreGState() }
 private func shapePath(_ s:ShapeKind?,_ r:CGRect,_ c:CGContext){switch s{case .ellipse:c.addEllipse(in:r);case .line,.arrow:c.move(to:CGPoint(x:r.minX,y:r.minY));c.addLine(to:CGPoint(x:r.maxX,y:r.maxY));case .diamond:c.move(to:CGPoint(x:r.midX,y:r.minY));c.addLine(to:CGPoint(x:r.maxX,y:r.midY));c.addLine(to:CGPoint(x:r.midX,y:r.maxY));c.addLine(to:CGPoint(x:r.minX,y:r.midY));c.closePath();case .triangle:c.move(to:CGPoint(x:r.midX,y:r.minY));c.addLine(to:CGPoint(x:r.maxX,y:r.maxY));c.addLine(to:CGPoint(x:r.minX,y:r.maxY));c.closePath();default:c.addRect(r)}}
 private func drawPath(_ points:[CanvasPoint],color:RGBAColor,width:Double,opacity:Double,context c:CGContext){guard let first=points.first else{return};c.setStrokeColor(NSColor(red:color.red,green:color.green,blue:color.blue,alpha:color.alpha*opacity).cgColor);c.setLineCap(.round);c.setLineJoin(.round);c.move(to:first.cgPoint);for p in points.dropFirst(){c.addLine(to:p.cgPoint)};c.setLineWidth(width);c.strokePath()}
 private func canvasPoint(_ event:NSEvent)->CGPoint{guard let store else{return .zero};let p=convert(event.locationInWindow,from:nil);return CGPoint(x:(p.x-store.pan.width)/store.zoom,y:(p.y-store.pan.height)/store.zoom)}
 override func mouseDown(with event:NSEvent){window?.makeFirstResponder(self);guard let store else{return};let p=canvasPoint(event);dragStart=p;if [.pen,.highlighter,.pixelEraser,.laser].contains(store.tool){live=[CanvasPoint(x:p.x,y:p.y,pressure:event.pressure,time:event.timestamp)]}else if store.tool == .select{let hit=store.current.elements.reversed().first{ $0.bounds.cgRect.insetBy(dx:-8,dy:-8).contains(p)};if let hit{if event.modifierFlags.contains(.shift){if store.selection.contains(hit.id){store.selection.remove(hit.id)}else{store.selection.insert(hit.id)}}else{store.selection=[hit.id]}}else{store.selection=[]}};needsDisplay=true}
 override func mouseDragged(with event:NSEvent){guard let store,let start=dragStart else{return};let p=canvasPoint(event);switch store.tool{case .pen,.highlighter,.pixelEraser,.laser:live.append(CanvasPoint(x:p.x,y:p.y,pressure:max(0.2,event.pressure),time:event.timestamp));case .hand:store.pan.width += event.deltaX;store.pan.height += event.deltaY;case .select:let dx=p.x-start.x,dy=p.y-start.y;store.mutate{b in for i in b.elements.indices where store.selection.contains(b.elements[i].id) && !b.elements[i].locked{b.elements[i].bounds.x+=dx;b.elements[i].bounds.y+=dy}};dragStart=p;default:break};needsDisplay=true}
 override func mouseUp(with event:NSEvent){guard let store,let start=dragStart else{return};let p=canvasPoint(event);if store.tool == .pen || store.tool == .highlighter{let points=ElementEditor.simplify(live);let rect=boundsFor(points);let kind:ElementKind=store.tool == .pen ? .stroke:.highlighter;store.mutate{$0.elements.append(BoardElement(kind:kind,points:points,bounds:RectValue(rect),stroke:toolColor(store.tool),width:toolWidth(store.tool)))} else if store.tool == .strokeEraser{store.mutate{$0.elements.removeAll{$0.bounds.cgRect.insetBy(dx:-10,dy:-10).contains(p)}}}else if [.rectangle,.ellipse,.line,.arrow,.diamond,.triangle,.frame].contains(store.tool){var end=p;if event.modifierFlags.contains(.shift){let d=max(abs(p.x-start.x),abs(p.y-start.y));end=CGPoint(x:start.x+(p.x>=start.x ? d:-d),y:start.y+(p.y>=start.y ? d:-d))};let r=CGRect(x:min(start.x,end.x),y:min(start.y,end.y),width:abs(end.x-start.x),height:abs(end.y-start.y));let shape:ShapeKind=switch store.tool{case .ellipse:.ellipse;case .line:.line;case .arrow:.arrow;case .diamond:.diamond;case .triangle:.triangle;default:.rectangle};store.mutate{$0.elements.append(BoardElement(kind:store.tool == .frame ? .frame:.shape,bounds:RectValue(r),shape:shape,width:2))}}else if store.tool == .text || store.tool == .sticky{let r=CGRect(x:p.x,y:p.y,width:220,height:store.tool == .sticky ? 160:52);store.mutate{$0.elements.append(BoardElement(kind:store.tool == .sticky ? .sticky:.text,bounds:RectValue(r),text:store.tool == .sticky ? "New note":"Text",fill:store.tool == .sticky ? RGBAColor(red:1,green:0.86,blue:0.34,alpha:0.45):nil))}};live=[];dragStart=nil;needsDisplay=true}
 override func magnify(with event:NSEvent){guard let store else{return};store.zoom=min(8,max(0.1,store.zoom*(1+event.magnification)));needsDisplay=true}
 override func scrollWheel(with event:NSEvent){guard let store else{return};store.pan.width += event.scrollingDeltaX;store.pan.height += event.scrollingDeltaY;needsDisplay=true}
 private func boundsFor(_ p:[CanvasPoint])->CGRect{guard let f=p.first else{return .zero};var r=CGRect(x:f.x,y:f.y,width:1,height:1);for q in p.dropFirst(){r=r.union(CGRect(x:q.x,y:q.y,width:1,height:1))};return r}
 private func toolColor(_ t:SlateTool)->RGBAColor{t == .highlighter ? RGBAColor(red:1,green:0.72,blue:0.08,alpha:1):.ink};private func toolWidth(_ t:SlateTool)->Double{t == .highlighter ? 18:3}
 override func draggingEntered(_ sender:NSDraggingInfo)->NSDragOperation{.copy}
 override func performDragOperation(_ sender:NSDraggingInfo)->Bool{guard let store else{return false};let p=convert(sender.draggingLocation,from:nil);if let s=sender.draggingPasteboard.string(forType:.string){store.mutate{$0.elements.append(BoardElement(kind:.text,bounds:RectValue(x:p.x,y:p.y,width:300,height:100),text:s))};return true};return false}
}
